### ISSUE TITLE
Problems building under Linux

### ISSUE THREAD

**Issue by blakemcbride** [barry-scott/BarrysEmacs#1]
Hi,

I am operating on 64 bit LinuxMint 17.1.  Here is my build log:

blake@blake-sony ~ $ mkdir -p ~/wc/git
blake@blake-sony ~ $ git clone https://github.com/barry-scott/BarrysEmacs.git
Cloning into 'BarrysEmacs'...
remote: Counting objects: 5717, done.
remote: Compressing objects: 100% (1778/1778), done.
remote: Total 5717 (delta 3889), reused 5705 (delta 3877), pack-reused 0
Receiving objects: 100% (5717/5717), 5.45 MiB | 333.00 KiB/s, done.
Resolving deltas: 100% (3889/3889), done.
Checking connectivity... done.
blake@blake-sony ~ $ cd BarrysEmacs/Builder/
blake@blake-sony ~/BarrysEmacs/Builder $ . builder_custom_init.sh 
Info: WorkingDir:
Info: Config Platform: Linux
Info: Python Version: 3.4
blake@blake-sony ~/BarrysEmacs/Builder $ ./build-linux.sh 
linux.mak:41: **\* unsupported BUILDER_CFG_PLATFORM of Linux .  Stop.
blake@blake-sony ~/BarrysEmacs/Builder $

Thanks!

Blake McBride

**Comment by barry-scott** [comment]
> On 25 Jun 2016, at 20:14, Blake McBride notifications@github.com wrote:
> 
> Hi,
> 
> I am operating on 64 bit LinuxMint 17.1. Here is my build log:
> 
> blake@blake-sony ~ $ mkdir -p ~/wc/git
> blake@blake-sony ~ $ git clone https://github.com/barry-scott/BarrysEmacs.git
> Cloning into 'BarrysEmacs'...
> remote: Counting objects: 5717, done.
> remote: Compressing objects: 100% (1778/1778), done.
> remote: Total 5717 (delta 3889), reused 5705 (delta 3877), pack-reused 0
> Receiving objects: 100% (5717/5717), 5.45 MiB | 333.00 KiB/s, done.
> Resolving deltas: 100% (3889/3889), done.
> Checking connectivity... done.
> blake@blake-sony ~ $ cd BarrysEmacs/Builder/
> blake@blake-sony ~/BarrysEmacs/Builder $ . builder_custom_init.sh 
> Info: WorkingDir:
> Info: Config Platform: Linux
> Info: Python Version: 3.4
> blake@blake-sony ~/BarrysEmacs/Builder $ ./build-linux.sh 
> linux.mak:41: **\* unsupported BUILDER_CFG_PLATFORM of Linux . Stop.
> blake@blake-sony ~/BarrysEmacs/Builder $
> 
> I work on fedora and that code is fully working.

Look in Builder/builder_custom_init.sh where it figures out the distro detect code
that is needed. Then let me have pr with the code changes.

You need to add code to detect your distro.

Then look in linux.mak for how the build is changed by the distro setting.

Then you should be able to get the editor built.

The next problem will be that I have not been near a debian type system for years
so the dpkg code will almost certainly be wrong.

Barry

**Comment by blakemcbride** [comment]
The great thing about this whole system is that others can help flush this kind of stuff out.  I'll send you a fix soon.  Thanks!

**Comment by blakemcbride** [comment]
This seems to have fixed that problem:

```
  diff --git a/Builder/builder_custom_init.sh b/Builder/builder_custom_init.sh
  index 21d7d53..13c3500 100755
  --- a/Builder/builder_custom_init.sh
  +++ b/Builder/builder_custom_init.sh
  @@ -30,10 +30,7 @@ Linux)

       elif [ -e /etc/lsb-release ]
       then
  -        if [ "$( grep "DISTRIB_ID=Ubuntu" /etc/lsb-release )" = "DISTRIB_ID=Ubuntu" ]
  -        then
               export BUILDER_CFG_PLATFORM=Linux-Ubuntu
  -        fi

       elif [ -e /etc/os-release ]
       then

```

**Comment by barry-scott** [comment]
I have strip this back in the code to simplify things.
There is only Linux-Fedora and Linux-Debian now.

Which I may well remove as I doubt that this source will be used to create binary kits
anymore.

Please test current source and instructions.
