### ISSUE TITLE
Shouldn't use fixed paths in build

### ISSUE THREAD

**Issue by blakemcbride** [barry-scott/BarrysEmacs#2]
Hi,

Just two professional opinions regarding the build process:
1.  You should not be determining paths on my machine (like ~/wc/git  and ~/BarrysEmacs).  You may use any directory structure you like, but it should all be relative to a directory of my choosing.
2.  It is unreasonable for you to require two paths to build your editor (again like ~/wc/git  and ~/BarrysEmacs).  Allow me to install the source in any directory I choose, and then everything should be build from that single parent directory.

These are pretty universal standards.

On the other hand, thank you very much for releasing the source.  It and your work are greatly appreciated!

Blake McBride

**Comment by barry-scott** [comment]
> On 25 Jun 2016, at 21:38, Blake McBride notifications@github.com wrote:
> 
> Hi,
> 
> Just two professional opinions regarding the build process:
> 
> You should not be determining paths on my machine (like ~/wc/git and ~/BarrysEmacs). You may use any directory structure you like, but it should all be relative to a directory of my choosing.

Its an instruction bug.
I expected you to cd into wc/git then clone.
I can update the instructions.

**Comment by barry-scott** [comment]
As a bit of background I have a whole set of tools that I use and I am trying to
simplify the instructions and avoid imposing my tool chain on others.

I am not surprised that the instructions need debugging.

I just spotted that one env var need setting. BUILDER_TOP_DIR to the BarrysEmacs folder.

Or I say use my builder tool, also on github.

Barry

**Comment by barry-scott** [comment]
Please test current code and instructions.
