### ISSUE TITLE
Hard-coding /Kits directory

### ISSUE THREAD

**Issue by blakemcbride** [barry-scott/BarrysEmacs#3]
Here is my build log:

Info: Creating ../Kits/FreeBSD/PLIST.template
Info: Creating ../Kits/Windows/bemacs_version.py
Info: Creating ../Kits/OpenBSD/DESC
Info: Creating ../Kits/OpenBSD/PLIST.template
if [ ! -e /Kits/Linux/DPKG/tree/usr/local/bemacs8/share/doc/bemacs ]; then mkdir -p /Kits/Linux/DPKG/tree/usr/local/bemacs8/share/doc/bemacs; fi
mkdir: cannot create directory ‘/Kits’: Permission denied
make: **\* [/Kits/Linux/DPKG/tree/usr/local/bemacs8/share/doc/bemacs] Error 1

Should be doing anything at /Kits

**Comment by barry-scott** [comment]
Sigh... don't you every research the problems you see in code?

If you had you would have seen that /Kit is coded as ${BUILDER_TOP_DIR}/Kits.

I have defaulted BUILDER_TOP_DIR}/ in builder_custom_init.sh
