### ISSUE TITLE
Is there not a shell in version 8.4.0 ?

### ISSUE THREAD

**Issue by romario89** [barry-scott/BarrysEmacs#6]
I'm using both version of 7.2 on WinXP and 8.4..0 on Win7. I've noticed that there is no shell option in 8.4.0 whereas it's there in version 7.2. I wonder if shell is available in any version of 8.x.

**Comment by barry-scott** [comment]
> On 27 Jul 2018, at 18:40, romario <notifications@github.com> wrote:
> 
> I'm using both versions of 7.2 on my WinXP and 8.4..0 on my Win7. I noticed that there's no shell option in 8.4.0 whereas it's there in version 7.2. I wonder if shell is available in any version of 8.x.
> 
> 


I found it hard to have the shell feature work for the current generation of code.
I recall it was hard to figure out how to merge the process management into the Qt event loop.

I did make execute-monitor-command work that allows you to run a single command and get its output.

Is that good enough for what you need a shell for?

Barry

**Comment by romario89** [comment]
Thank you for the reply. I 'd like to have the shell for trying codes such as Python scripts inside the editor.  I couldn't find the  execute-monitor-command among the menu items, is it invoked through a key combination?

**Comment by barry-scott** [comment]
> On 27 Jul 2018, at 23:10, romario <notifications@github.com> wrote:
> 
> Thank you for the reply. I 'd like to have the shell for trying codes such as Python scripts inside the editor. I couldn't find the execute-monitor-command among the menu items, is it invoked through a key combination?
> 
> 

You could do this with the execute-monitor-command but the down side would be that you cannot Ctrl-C you python script to stop it if it loops.
Personally I start a CMD window along side the emacs windows and test my python on the CMD window.

However if you want to try execute-monitor-command then you run it by typing:

ESC-x execute-monitor-command RETURN

At the Command: prompt type the command you want to run.

The alternalive is the type ESC-ESC to bring up the mini buff window and type this into it:

(execute-monitor-command "python myscript.py arg")

Then type ESC-ESC to execute the command.

To repeat just type ESC-ESC again.

Barry

**Comment by romario89** [comment]
Thank you for the suggestion. I tried the execute-monitor-command and it did work.
