### ISSUE TITLE
Seems it's too much effort to build this version of Emacs

### ISSUE THREAD

**Issue by ReneFroger** [barry-scott/BarrysEmacs#9]
An user mentioned it required too much effort to build:

https://www.reddit.com/r/emacs/comments/1175qcp/goslings_implementation_of_emacs_now_open_source/j9sos35/

It's still unclear what he means with Slackware.

**Comment by barry-scott** [comment]
Indeed its unclear, there is no detail to work from.

The Barry's Emacs build system support Windows, macOS, Fedora, EPEL, debian, ubuntu and NetBSD at the moment.
I'm happy to support more OS.

If you are on reddit please reply asking them to engage with me.
Either with an issue here or email or groups.io.

Barry
